apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vault-virtual-service
  namespace: vault-example
spec:
  hosts:
  - "vault.sujangcloud.uk"
  gateways:
  - istio-system/istio-ingress-gateway
  http:
  - match:
    - uri:
        prefix: /

    route:
    - destination:
        host: vault-example-ui.vault-example.svc.cluster.local
        port:
          number: 8080




